In [1]:
import numpy as np
def orientation_to_dcm(forward, up=np.array([0,0,1])):
    f = np.array(forward, dtype=float)
    f /= np.linalg.norm(f)
    # if forward is (anti)parallel to up, choose a default right axis
    if np.linalg.norm(np.cross(up, f)) < 1e-8:
        # forward parallel to up -> no yaw info; choose right = +x
        r = np.array([1.0, 0.0, 0.0])
        # if forward is -up (i.e. [0,0,-1]) flip right to keep right-handedness
        if np.dot(f, up) < 0:
            r = -r
    else:
        r = np.cross(up, f)
        r /= np.linalg.norm(r)
    u = np.cross(f, r)
    R = np.column_stack((r, u, f))
    return R

In [ ]:
a=[1,1,1]
a/=np.linalg.norm(a)
print(a)
orientation_to_dcm(a)@[0,0,1]

array([0.57735027, 0.57735027, 0.57735027])

In [7]:
g=9.8 #m/s^2
R_earth=6371e3 #meter
dt=10 #seconds
total_time=60*60
latitude= 19.5 / 180 * np.pi #radians
w_earth=2*np.pi/24/60/60 #rad/s
G_force_limit=4
p=np.array([6039478.38247853,  580788.51691171, 2138691.4636333 ])
t=4+0.74*60
ip=[np.array([R_earth*np.cos(latitude),0,R_earth*np.sin(latitude)])]

In [9]:
theta=w_earth*t
Rz = np.array([[ np.cos(theta), np.sin(theta), 0],
                [ -np.sin(theta),  np.cos(theta), 0],
                [0,0,1]        ])
p_2=Rz@p

In [10]:
p_2

array([6041485.19671994,  559527.5253424 , 2138691.4636333 ])

In [11]:
ip

[array([6005568.93974827,       0.        , 2126683.50017835])]

In [2]:
import numpy as np
np.array([6026911.19241123, 699253.82558137, 2138691.4636333])-np.array([6005.57,0,2126.68])*1e3

array([ 21341.19241123, 699253.82558137,  12011.4636333 ])

In [4]:
np.array([ 21341.19241123, 699253.82558137,  12011.4636333 ])/1e3

array([ 21.34119241, 699.25382558,  12.01146363])

In [5]:
w_earth=2*np.pi/24/60/60
np.array([ 356.8940986,  5314.96084655,  126.38282874])-np.cross(np.array([0,0,w_earth]),np.array([6039478.38247853,  580788.51691171, 2138691.4636333 ]))

array([ 399.13023142, 4875.75758456,  126.38282874])